from collections.abc import Mapping
from typing import Any, Protocol

from apps.todos.contracts.dto import TodoData, TodoQuery


class TodoRepository(Protocol):
    def list(self, *, query: TodoQuery) -> list[TodoData]: ...

    def get_by_id(self, *, todo_id: int) -> TodoData | None: ...

    def create(self, *, attributes: Mapping[str, Any]) -> TodoData: ...

    def update(self, *, todo_id: int, changes: Mapping[str, Any]) -> TodoData: ...

    def delete(self, *, todo_id: int) -> None: ...
